USE BikeStores;

CREATE TABLE production.trainer
(
	id INT IDENTITY (1,1) PRIMARY KEY,
	firstName VARCHAR (50) NOT NULL,
	lastName VARCHAR (50) NOT NULL,
	email VARCHAR (255) NOT NULL UNIQUE,
	phone VARCHAR (25),
	poke_ID INT NOT NULL,
	FOREIGN KEY (poke_ID)
		REFERENCES production.pokemon (id)
		ON DELETE CASCADE ON UPDATE CASCADE
);